### ISSUE TITLE
environment-variables not working

### ISSUE THREAD

**Issue by joa-queen** [aws-actions/amazon-ecs-render-task-definition#136]
The error:
```Warning: Unexpected input(s) 'environment-variables', valid inputs are ['task-definition', 'container-name', 'image']```

The definition:
```
- name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}
        environment-variables: |
          TEST=something
```

**Comment by kubical-moncef** [comment]
Hello @joaqtor ,
As you can see in the releases section, the latest one (v1.0.24) has been released on August 30th. However the PR which enables handling of env variables (https://github.com/aws-actions/amazon-ecs-render-task-definition/pull/114) has been merged on October 14th. 
While waiting for a new release which includes the PR mentioned above, you can fix your github workflow by using the master ref :
 ```
- name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@*master*
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}
        environment-variables: |
          TEST=something

```
