### ISSUE TITLE
Render for more than one container 

### ISSUE THREAD

**Issue by felipem1210** [aws-actions/amazon-ecs-render-task-definition#228]
I think that a nice feature would be to allow to add more than one container in container-name input.
The purpose is that I have cases when I have more than one container inside my task definition. And I need these containers use the same image and same environment variables.  

I saw in the README that you suggest using the action more than once to achieve this, but I need to do it in a more programatic way,.

**Comment by oliakremmyda** [comment]
Hello, we also have this usecase of multiple containers inside the task definition and the solution of calling the action many times is not that portable and re-usable. 

Do you plan in the near feature to support rendering more than one container in the same action?

**Comment by oliakremmyda** [comment]
Is there any update on this?

**Comment by felipem1210** [comment]
It seems that nobody of the contributors maintain this repo. I had to fork the repo and merge my PR to have the feature

**Comment by kent-ps** [comment]
hi, we also need this feature. Any update on this?

**Comment by derekkraan** [comment]
I ran into this last week and wanted to share my solution. I have two containers in the same task definition that both need to be updated to the same image reference. I ended up chaining them, and it works perfectly.

```
      - name: Fill in the new image ID in the Amazon ECS task definition                                                                                                                                                                                                                   
        id: task-def                                                                                                                                                                                                                                                                       
        uses: aws-actions/amazon-ecs-render-task-definition@v1                                                                                                                                                                                                                             
        with:                                                                                                                                                                                                                                                                              
          task-definition-arn: ${{ env.ECS_TASK_DEFINITION_ARN }}                                                                                                                                                                                                                          
          container-name: app                                                                                                                                                                                                                                                              
          image: ${{ steps.build-image.outputs.image }}                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                           
      - name: Fill in the new image ID in the Amazon ECS task definition                                                                                                                                                                                                                   
        id: task-def2                                                                                                                                                                                                                                                                      
        uses: aws-actions/amazon-ecs-render-task-definition@v1                                                                                                                                                                                                                             
        with:                                                                                                                                                                                                                                                                              
          task-definition: ${{ steps.task-def.outputs.task-definition }}                                                                                                                                                                                                                   
          container-name: db_migrations                                                                                                                                                                                                                                                    
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition                                                                                                                                                                                                                                            
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a                                                                                                                                                                                       
        with:                                                                                                                                                                                                                                                                              
          task-definition: ${{ steps.task-def2.outputs.task-definition }}                                                                                                                                                                                                                  
          service: ${{ env.ECS_SERVICE }}                                                                                                                                                                                                                                                  
          cluster: ${{ env.ECS_CLUSTER }}                                                                                                                                                                                                                                                  
          wait-for-service-stability: true
```

Maybe this will help someone looking at this later, wondering what to do.
