### ISSUE TITLE
Q: Error: Invalid task definition: Could not find container definition with matching name

### ISSUE THREAD

**Issue by vitalykarasik** [aws-actions/amazon-ecs-render-task-definition#232]
I'm using this action recently and it works fine for many services. But yesterday I added a new one, and rendering fails with "Error: Invalid task definition: Could not find container definition with matching name".
As far as I see, my task definition uses the same container name as I pass to the action, so I couldn't understand what is wrong here.
```
"containerDefinitions": [
        {
            "name": "fc-core-pay-bin-server",
```

```
Run aws-actions/amazon-ecs-render-task-definition@v1
  with:
    task-definition: xxxx-task-definition.json
    container-name: fc-core-pay-bin-server
```

TIA,
Vitaly

**Comment by vitalykarasik** [comment]
Update: the same task definition and GH workflow work with amazon-ecs-render-task-definition@v1.0.24.
I'll be glad to send you debug output in private.

**Comment by vitalykarasik** [comment]
Any updates?

**Comment by roman-parkhunovskyi** [comment]
v1.1.2 appears to work, thanks @vitalykarasik. But it has [set-output deprecation notice](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) and might stop working after May 31.
v1.1.3 has this bug, described in the issue.

**Comment by vitalykarasik** [comment]
@roman-parkhunovskyi  - it's good news for me, so I'm not crazy :-)
My plan B is forking v1.1.2, update @actions/core and rebuild - I already did that for about GHA (Slack notification). Of course, I'll publish it.
>[set-output deprecation notice](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) and might stop working after May 31

Did  GH already announce this date?

**Comment by brennh-animoca** [comment]
I'm also having this issue. When will they fix this?

**Comment by brennh-animoca** [comment]
Was able to resolve. Issue was lack of quotes around the name in the yaml file. The yaml file would parse but this would fail. Make sure that your container name is quoted.

**Comment by vitalykarasik** [comment]
@brennh-animoca  - thanks! Can you please provide more details:
1) "I'm also having this issue" - your original config didn't work with v1.1.3, but worked with v1.1.2?
2) "Issue was lack of quotes around the name in the yaml file"  - do you mean task definition file? I'm using JSON format, and as far as I see all strings are quoted. Can you please share some example?

**Comment by vitalykarasik** [comment]
@brennh-animoca - thank you for the details.
Weird...
As far as I can see, all my task definitions are 99% similar, and I had an issue with one of them with v1.1.3.
It's more or less 
```
"containerDefinitions": [
        {
            "name": "servicename",
            "image": "XXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/server-name:hashhashhashhashhash",
```

**Comment by Abdullah-Shahen** [comment]
I was able to render a task def with this action.  In one project it works just fine, in the other it does not work, and it throws `Invalid task definition: Could not find container definition with matching name`

Both projects have the same task def. Structure.  This is super confusing. 

Any fix or workaround?

**Comment by Abdullah-Shahen** [comment]
Strange... 
Even with `Run aws-actions/amazon-ecs-render-task-definition@v1` getting same: `Error: Invalid task definition: Could not find container definition with matching name` 

Here my current action step:
```yml
      - name: Create new AWS ECS task definition on Stage (DEV)
        id: dev-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1.1.3
        with:
          task-definition: task-definition.json
          container-name: ${{ inputs.ECS_CONTAINER_NAME }}
          image: ${{ steps.dev-image-build.outputs.image }}
```

I'm wondering if you really want to keep this issue closed.

**Comment by vitalykarasik** [comment]
@Abdullah-Shahen - does your workflow works with v1.1.2?
My workflow seems almost the same:

```
- name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}
```

and relevant of a task definition is 

```
"containerDefinitions": [
        {
            "name": "core-p",
            "image": "xxxxxx.dkr.ecr.us-east-1.amazonaws.com/core-p:7da9b252999a69d0cc1ab1ed52f769f29f960e1d",
```

Again - I have no idea why I met this issue in Feb, but cannot reproduce now - neither action not my task definitions weren't modified as far as I see...
