### ISSUE TITLE
Bug: Invalid task definition: Could not find container definition with matching name

### ISSUE THREAD

**Issue by Abdullah-Shahen** [aws-actions/amazon-ecs-render-task-definition#246]
I'm using this action with the latest version as well as with the v1.1.3, for one ECS Service, it works just fine, for the other service it does not. Rendering of the ECS Task fails with `Error: Invalid task definition: Could not find container definition with matching name`.
I have checked the ECS Task JSON and **it contains the container name.** 

Both Services are identical in terms of ECS Task def structure. Just Env. vars are different.

Here my current action step:
```yml
      - name: Create new AWS ECS task definition on Stage (DEV)
        id: dev-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1.1.3 # Also used latest and it did not work.
        with:
          task-definition: task-definition.json
          container-name: ${{ inputs.ECS_CONTAINER_NAME }}
          image: ${{ steps.dev-image-build.outputs.image }}
``` 

@vitalykarasik was somehow able to get it to work (see [Issue](https://github.com/aws-actions/amazon-ecs-render-task-definition/issues/232)), still we don't know why it does not work in this case. 

Any Idea or hint on how to fix this is highly appreciated.
