### ISSUE TITLE
how to update the awslogs-group?

### ISSUE THREAD

**Issue by sombriks** [aws-actions/amazon-ecs-render-task-definition#254]
any example on how do i could use the action to set awslogs-group inside my task definition?

**Comment by bhaktatejas922** [comment]
`xample inside` a github workflow: 

```
      - name: Render Amazon ECS task definition for backend container
        if: matrix.build == 'backend'
        id: render-backend-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.APPLICATION_TASK_DEFINITION }}
          container-name: backend
          image: ${{ steps.build-backend-image.outputs.image }}
          log-configuration: awslogs,awslogs-group=${{ needs.prepare.outputs.log_group }},awslogs-stream-prefix=backend
```
