### ISSUE TITLE
How to pass environment variable file to the action?

### ISSUE THREAD

**Issue by binjiezhao-alcumus** [aws-actions/amazon-ecs-render-task-definition#275]
We need to pass environment variable file stored in S3 to the render action. See this aws doc:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html

How do we do it?

**Comment by LiJell** [comment]
```
"containerDefinitions": [
      ...
   "environmentFiles": [
          {
            "value": "arn:aws:s3:::environment.env",
            "type": "s3"
          }
        ],
      ...
]
```
      
like above under containerDefinitions

**Comment by binjiezhao-alcumus** [comment]
Yes exactly. 
We have an env file for each environment: dev, test etc. Currently this is solved by an extra bash step to replace the file name for env.

**Comment by scott-doyland-burrows** [comment]
Being able to envars would be really helpful. Not just the S3 type.

And any other parameters that are likely to be configured as part of CI/CD workflow.

**Comment by ctjhoa** [comment]
If I'm not mistaken, this feature is already implemented but not documented.
https://github.com/aws-actions/amazon-ecs-render-task-definition/commit/a55093efad2004162ace90df979bbaf2d6df3910#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R32
From my understanding you can specify each arn like this:
```
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ vars.FARGATE_TASK_DEFINITION }}
          container-name: ${{ vars.FARGATE_CONTAINER_NAME }}
          image: ${{ secrets.ECR_IMAGE_NAME }}
          env-files: |
            arn:aws:s3:::s3_bucket_name/envfile1_object_name.env
            arn:aws:s3:::s3_bucket_name/envfile2_object_name.env
  
```
