### ISSUE TITLE
Need a way to remove Docker commands

### ISSUE THREAD

**Issue by scott-doyland-burrows** [aws-actions/amazon-ecs-render-task-definition#301]
If I have setup a Docker command to be passed to the conatiner, eg:

```
    - name: Render ECS task definition
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: xxx
        container-name:xxx
        image: xxx
        command: "echo, hello"
```

but then later want to remove the command completely, so in my task def it will show as an empty array ```[]```, then it seems I cannot do that.  Passing a null value to ```command:``` still keeps the old command from the previous run.
