### ISSUE TITLE
Deployment fails with: Unexpected key 'enableFaultInjection' found in params

### ISSUE THREAD

**Issue by sighmon** [aws-actions/amazon-ecs-render-task-definition#363]
We have a failing GitHub Action with this code:

```yaml
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: false
```

Error:

```bash
Error: Failed to register task definition in ECS: Unexpected key 'enableFaultInjection' found in params
Error: Unexpected key 'enableFaultInjection' found in params
```

Looks to have been introduced here: https://github.com/search?q=repo%3Aaws-actions%2Famazon-ecs-render-task-definition+enableFaultInjection&type=pullrequests

## Solution

Bump task definition for deployment to `v2`:

```yaml
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: false
```
