### ISSUE TITLE
There are multiple containers in one task. Can I specify multiple container names for container-name?

### ISSUE THREAD

**Issue by ogasawaraShinnosuke** [aws-actions/amazon-ecs-render-task-definition#4]
### Current

```yml
  - name: Fill in the new image ID in the Amazon ECS task definition
       id: task-def
       uses: aws-actions/amazon-ecs-render-task-definition@v1
       with:
         task-definition: task-definition.json
         container-name: sample-app
         image: ${{ steps.build-image.outputs.image }}
```

### Asking

```yml
  - name: Fill in the new image ID in the Amazon ECS task definition
       id: task-def
       uses: aws-actions/amazon-ecs-render-task-definition@v1
       with:
         task-definition: task-definition.json
         container-name: 
           - sample-app1
           - sample-app2
         image: ${{ steps.build-image.outputs.image }}
```

**Comment by clareliguori** [comment]
You can chain this action to fill in multiple images:
```yaml
    - name: Render Amazon ECS task definition
      id: render-web-container-1
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: web1
        image: amazon/amazon-ecs-sample:latest

    - name: Render 2
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ steps.render-web-container-1.outputs.task-definition }}
        container-name: web2
        image: amazon/amazon-ecs-sample:latest
```
