### ISSUE TITLE
Task Definition with specific file path takes 2x times for deployment

### ISSUE THREAD

**Issue by pratikg117** [aws-actions/amazon-ecs-render-task-definition#53]
I am using aws-actions/amazon-ecs-render-task-definition@v1 for ecs deployment,  I have multiple task definition file depending on various env. When specified with file path the build time doubles

**task-definition:** 
When specified with a file path takes lots of time to deploy

**Total Build Time: ~ Approx. 4 - 5 min** 
```
 - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        **task-definition: task-definition.json**
        container-name: test
        image: ${{ steps.build-image.outputs.image }}
```

**Total Build Time: ~ Approx. 9 - 12 min** 
```
 - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        **task-definition: deployment/test/task-definition-test.json**
        container-name: test
        image: ${{ steps.build-image.outputs.image }}
```
