### ISSUE TITLE
“Error: Task definition file does not exist: ” when deploying Docker images to AWS ECS

### ISSUE THREAD

**Issue by naveen-9697** [aws-actions/amazon-ecs-render-task-definition#68]
I am trying to push docker images from GitHub Actions to AWS ECR then to ECS with a task to deploy the latest container in AWS ECS. 

I am using the default aws.config file with changes only for AWS ECR repository name, AWS ECS cluster name and it's service name and docker image details to push docker images to AWS ECR to which could then to deployed as containers to AWS ECS by defining tasks. And I got an error message with defining tasks to deploy to ECS(in the section "Fill in the new image ID in the Amazon ECS task definition" in aws.yml) and it is:
```
Error: Task definition file does not exist: ecs-task-definition.json
```

Some information to prove everything is in place(presumably):  
**Here's me checking the existence of file and pushing the task from my terminal to AWS ECS:**
[![enter image description here][2]][2]

And here's that very task definition with the revision number and task's family name shown in screenshot above:
[![enter image description here][3]][3]

**So, as you can see task-definition file does exist, but GitHub doesn't recognise it. What has caused this error and how do I fix this?**

**Here's the complete build screenshot:**
[![enter image description here][4]][4]

**and this is the error:**
[![enter image description here][5]][5]

And here's the part of my ".github/workflows/aws.yml" in my repo for task definition (file can be found [here in my repository][6])
```
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ecs-task-definition.json
        container-name: aws-dock-p-cont
        image: ${{ steps.build-image.outputs.image }}
```

Images are being pushed to my ECR repository without any problems, but the problem comes right before executing tasks to use those images and deploy as containers.

**EDIT:**
Here's the cluster I have used in aws.yml file:
[![enter image description here][7]][7]
Here's the role I have specified in the task json file:
[![enter image description here][8]][8]

I have done as described in [this article][9].

  [1]: https://github.com/actions/starter-workflows/blob/b4fa2522d2fe556c03cc194dcf659b1eb9f03b77/ci/aws.yml
  [2]: https://i.stack.imgur.com/XQcDa.png
  [3]: https://i.stack.imgur.com/0Nnns.png
  [4]: https://i.stack.imgur.com/gkXIL.png
  [5]: https://i.stack.imgur.com/EijC1.png
  [6]: https://github.com/naveen-9697/docker-ci-cd-aws-practice/blob/master/.github/workflows/aws.yml
  [7]: https://i.stack.imgur.com/N390s.png
  [8]: https://i.stack.imgur.com/lXxct.png
  [9]: https://medium.com/javascript-in-plain-english/deploy-your-node-app-to-aws-container-service-via-github-actions-build-a-pipeline-c114adeb8903

**Comment by naveen-9697** [comment]
I hadn't uploaded the task defintion file to my github repo with the thought that the GitHub will pull it from my AWS account.

**Comment by chorsnell** [comment]
for anyone else finding this, it turns out `task-definition:` does not obey `working_directory`, so the relative path needs to be from the root of your repo

**Comment by ShyamPanj** [comment]
my task-defintion.json file is directly under repo. How should I specify the path?

**Comment by sandeepinsys** [comment]
> my task-defintion.json file is directly under repo. How should I specify the path?

In that case, path should be ./task-defintion.json

**Comment by RulerOf** [comment]
In my case, I had forgotten to run the checkout step.

**Comment by JohnQ1981** [comment]
Please anyone can help, failing at the same step as mentioned above. and i have my 
![image](https://user-images.githubusercontent.com/69947888/191995218-f8ef276c-cc50-4117-b254-d81bbdb4e4bd.png)

and my github is https://github.com/JohnQ1981/teachermonsters




env:
    AWS_REGION: us-east-2
    ECR_REPOSITORY: mfedockertest
    ECS_SERVICE: mfedockertest-service
    ECS_CLUSTER: mfedockertest-cluster
    ECS_TASK_DEFINITION: ./task-definition.json
    CONTAINER_NAME: mfedockertest-task-definition
    AWS_DEFAULT_REGION: us-east-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Error: Task definition file does not exist: ./task-definition.json

**Comment by tatianafrank** [comment]
> Please anyone can help, failing at the same step as mentioned above. and i have my ![image](https://user-images.githubusercontent.com/69947888/191995218-f8ef276c-cc50-4117-b254-d81bbdb4e4bd.png)
> 
> ![image](https://user-images.githubusercontent.com/69947888/191995731-885fabef-d5f8-4c42-ad65-5e0825336544.png)
> 
> and my github is https://github.com/JohnQ1981/teachermonsters
> 
> env: AWS_REGION: us-east-2 ECR_REPOSITORY: mfedockertest ECS_SERVICE: mfedockertest-service ECS_CLUSTER: mfedockertest-cluster ECS_TASK_DEFINITION: ./task-definition.json CONTAINER_NAME: mfedockertest-task-definition AWS_DEFAULT_REGION: us-east-2 AWS_ACCESS_KEY_ID: *** AWS_SECRET_ACCESS_KEY: *** Error: Task definition file does not exist: ./task-definition.json

because your file is .yml but your path says .json

**Comment by islamsalah2020** [comment]
I faced the same issue, then I figured out that I need to download the task definition first then update it with the new container image. that solved the issue and I was able to deploy to ECS.


```
- name: Download task definition
      run: |
          aws ecs describe-task-definition --task-definition ${{ vars.MY_ECS_TASK_DEFINITION }} \
          --query taskDefinition > task-definition.json
      
 - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
          task-definition: task-definition.json
          container-name: ${{ vars.MY_CONTAINER_NAME   }}
          image: ${{ steps.build-image.outputs.image }}
```
